config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts, path_names: { sign_in: 'log_in' }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  require 'sidekiq/web'

  devise_scope :account do
    unauthenticated do
      root 'pages#home', as: :root
    end

    authenticate :account, lambda { |u| u.super_admin? || Rails.env.development? } do
      mount Sidekiq::Web => '/sidekiq'
    end

    authenticated :account, lambda { |u| u.admin? } do
      root 'admin/accounts#index', as: :admin_authenticated_root

      scope module: :admin do
        resources :accounts, only: [:index]
      end
    end

    authenticated :account, lambda { |u| u.other? } do
      root 'admin/accounts#index', as: :other_authenticated_root
    end
  end

  # TODO: uncomment this when the articles are ready
  # resources :articles
  resource :contact, only: [:show, :create]

  get "/*id" => 'pages#show', as: :page, format: false, :constraints => HighVoltage::Constraints::RootRoute.new

  %w(400 404 406 422 500).each do |code|
    get code, to: 'errors#show', code: code
  end
end

app/views/partials/_analytics.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<%= javascript_include_tag 'https://www.googletagmanager.com/gtag/js?id=G-E7JYVJV79F', nonce: true %>
<%= javascript_tag nonce: true do %>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-E7JYVJV79F');
  gtag('set', { user_id: <%= current_account&.id %> });
<% end %>

app/views/partials/_breadcrumbs.html.erb
<div class="breadcrumbs">
  <div class="breadcrumbs__container">
    <span>
      <%= breadcrumbs.render(separator: '/', format: :inline) %>
    </span>
  </div>
</div>

app/views/partials/_footer.html.erb
<div class="footer print:display--none">
  <div class="footer__left">
    <%= link_to 'Cookies Policy', '#', target: :_blank %>
    <i class="mr--3 fa-solid fa-horizontal-rule fa-rotate-90"></i>
    <%= link_to 'Privacy Policy', '#', target: :_blank %>
    <i class="mr--3 fa-solid fa-horizontal-rule fa-rotate-90"></i>
    <%= link_to 'Terms of Service', '#', target: :_blank %>
    <i class="mr--3 fa-solid fa-horizontal-rule fa-rotate-90"></i>
    <%= link_to 'About BMX4', '#', target: :_blank %>
    <i class="mr--3 fa-solid fa-horizontal-rule fa-rotate-90"></i>
    <%# TODO: Add the correct support email %>
    <%= mail_to 'fabio@bmx4.com.br', 'Contact Support', target: :_blank %>
  </div>

  <div class="footer__right">
    &copy; <%= current_year %> BMX4 Technologies Ltd. All Rights Reserved.
  </div>
</div>

app/views/partials/_masquerade_banner.html.erb
<div id="masquerade-banner" class="bg--danger-dark color--red-50 p--4">
  <div class="page-container display--flex justify-content--center align-items--center">
    <div class="mr--6">Logged in as <%= current_account.name %></div>

    <%= link_to 'Logout', back_masquerade_path(current_account), class: 'button button--white button--danger' %>
  </div>
</div>

app/views/partials/_no_results.html.erb
<tr>
  <% breakpoints.each do |breakpoint| %>
    <td colspan="<%= breakpoint[:colspan] %>" class="<%= breakpoint[:class] %> td--fallback">
      <%= message %>
    </td>
  <% end %>
</tr>

app/views/partials/_toast.html.erb
<div data-controller="toast" data-toast-timeout-value="<%= timeout %>" class="toast toast--remove toast--<%= key %>">
  <div class="toast__message">
    <%= value %>
  </div>

  <i class="toast__close fa-regular fa-times" data-action="click->toast#remove"></i>
</div>

app/views/partials/_toasts.html.erb
<div id="toasts" class="toasts">
  <% flash.each do |key, value| %>
    <%= render partial: 'partials/toast', locals: { key: key, value: value, timeout: 0 } if value.present? %>
  <% end %>
</div>