config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts, path_names: { sign_in: 'log_in' }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  require 'sidekiq/web'

  devise_scope :account do
    unauthenticated do
      root 'pages#home', as: :root
    end

    authenticate :account, lambda { |u| u.super_admin? || Rails.env.development? } do
      mount Sidekiq::Web => '/sidekiq'
    end

    authenticated :account, lambda { |u| u.admin? } do
      root 'admin/accounts#index', as: :admin_authenticated_root

      scope module: :admin do
        resources :accounts, only: [:index]
      end
    end

    authenticated :account, lambda { |u| u.other? } do
      root 'admin/accounts#index', as: :other_authenticated_root
    end
  end

  # TODO: uncomment this when the articles are ready
  # resources :articles
  resource :contact, only: [:show, :create]

  get "/*id" => 'pages#show', as: :page, format: false, :constraints => HighVoltage::Constraints::RootRoute.new

  %w(400 404 406 422 500).each do |code|
    get code, to: 'errors#show', code: code
  end
end

app/views/admin/accounts/partials/index/_row.html.erb
<tr>
  <td class="font--semibold">
    <div class="font--semibold"><%= account.name %></div>
    <div class="cell--stacked"><%= account.email %></div>
  </td>

  <td>
    <div class="display--flex">
      <div class="pill pill--<%= account.account_type %> pill--bordered -pill-size--1 text--truncate"><%= account.account_type_i18n %></div>
    </div>
  </td>

  <td class="hidden--md-down"><%= l(account.updated_at, format: :short) %></td>
</tr>

app/views/admin/accounts/partials/index/_search_and_filter.html.erb
<%= search_form_for @q, url: accounts_path do |f| %>
  <div class="search-and-filter mb--6" data-controller="filter datepicker" data-action="click@window->filter#closeOutside">
    <div class="search">
      <%= f.search_field :full_name_or_email_cont,
                         autocomplete: 'off',
                         placeholder: 'Search by name or email...',
                         class: 'search__input' %>

      <%= f.button :submit, class: 'button search__button' do %>
        <i class="fa-solid fa-search -font-size--1 mb--1px"></i>
      <% end %>
    </div>

    <div class="filters mt--4">
      <div class="filter">
        <div class="filter__name" data-action="click->filter#toggleFilterMenu">
          <span>Type</span><i class="ml--3 fa-solid fa-chevron-down"></i>
        </div>

        <div class="filter__form">
          <% Account.account_types_i18n.each do |key, value| %>
            <%= filter_check_box('account_type_in', Account.account_types[key], value) %>
          <% end %>
        </div>
      </div>

      <%= f.submit 'Apply', class: 'button filter__button' %>
    </div>
  </div>
<% end %>